### PR TITLE
Update API protos subtree

### PR DESCRIPTION
**Pull request by bergundy**
## What was changed
In title

## Why?
I needed the latest versions of the API protos.

### CODE REVIEW

**Comment by Sushisource** [comment]
We should just change the docs to say subtree and include the instructions for updating them - submodules are comparatively a pain in the butt to update properly IMO. Subtrees on the other hand just work when someone pulls the repo. Unless we've got a compelling reason to switch I think I'd prefer to keep it as it

This is the right command for updating I believe:
`git subtree pull --prefix protos/api_upstream/ git://github.com/temporalio/api.git master --squash`

**Comment by bergundy** [comment]
Subtrees are a different type of pain from my experience but I'm fine with using them here since we never edit them directly from this repo.
I was confused by the docs and didn't realize we were using subtree.

**Comment by Sushisource** [comment]
I'll update the readme in https://github.com/temporalio/sdk-core/pull/195

**Comment by Sushisource** [comment]
Whoops, didn't mean to close, we can use this to update the subtree

**Pull request merged**
