### PR TITLE
Eliminate pending activations by returning new activations from complete

### PR DESCRIPTION
**Pull request by Sushisource**
## What was changed:
Return new activations from completing them, when required

## Why?
* Eliminates complexity around pending activations
* When you call poll, you always poll the server now
* When you poll, your activation is always for that task queue
* Eliminates question about how to "buffer" server responses if lang is dealing with pending activations - so closes https://github.com/temporalio/sdk-core/issues/91

## Checklist
TODO: 
- [ ] Saw stalling behavior if lang side didn't deal with returned activations from a completion (I think this is because workflow task timeout isn't working right)
- [ ] Cleanup pass

1. Closes issue: 
Closes https://github.com/temporalio/sdk-core/issues/91

2. How was this tested:
Existing & new tests

### CODE REVIEW

**Comment by Sushisource** [comment]
This may get closed in favor of another solution Max helped us realize that maintains the existing API by simply not starting any polling behavior until all pending activations are cleared out. Will leave as draft until I've had time to explore that.

**Comment by vitarb** [comment]
As far as I understand, we are not going to land this one, right?

**Comment by Sushisource** [comment]
> As far as I understand, we are not going to land this one, right?

Nope. Not for alpha at least. Want to keep it around if we revisit after.

**Comment by bergundy** [comment]
@Sushisource should we keep this draft?
I think we pretty much realized that this not the direction we're taking.

**Comment by Sushisource** [comment]
:wave: Goodbye, PR. I still think you're a nifty idea but it's been too long.

**Pull request closed without merging**
