### PR TITLE
Added the option to have the activity return a non-retryable error.

### PR DESCRIPTION
**Pull request by tdejager**
## What was changed

Added a `NonRetryableActivityError` type so that an ActivityFunction can return this Error and the activity is not retried. Hence, the workflow will fail.

## Why?

To be able to accommodate for the use-case where you as the user *know* that the activity should not be retried.

## Checklist

1. Closes: https://github.com/temporalio/sdk-core/issues/454

2. How was this tested:
Test was added `activity_non_retryable_failure_with_error` that uses the new function: `Failure::application_failure_from_error`.
  Also, created a manual test locally: Where an activity was used that returns the **new** error type. Not sure if a test could be added to `local_activities` to properly test the error conversion code? Could use some pointers here if this is deemed necessary :) Thanks!

4. Any docs updates needed?
 Not sure, as there is no currently published Rust docs.

### CODE REVIEW

**Comment by tdejager** [comment]
Seems to be failing. Is there any way I can check the output?

**Review by Sushisource — APPROVED** [review]
Awesome! LGTM. Thank you!

The CI is only failing b/c of a formatting issue. Run cargo fmt and it'll be good to go :+1:

**Comment by tdejager** [comment]
Formatted :)

**Comment by Sushisource** [comment]
Thanks for contributing!

**Pull request merged**
