### PR TITLE
Add missing license to test-utils crate

### PR DESCRIPTION
**Pull request by h7kanna**
## What was changed
Added license to test-utils crate to 'cargo-deny' failures

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Comment by h7kanna** [comment]
Yes with `license = { workspace = true }`

**Comment by Sushisource** [comment]
Sure, we can use one shared one and get rid of the line at the top.

**Comment by h7kanna** [comment]
Ok, made the required changes

**Review by Sushisource — APPROVED** [review]
Awesome! Thanks!

**Pull request merged**
